{% set name = "tip" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/309thEDDGE/tip/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 648a43540787e823d350e044dfbc10d79aabe0570c8c0a280aca9ad585bf1cbd   

build:
  skip: true  # [win and vc<14 or osx]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - make 4.*  # [unix]
    - ninja 1.*
    - cmake 3.*
    - pkgconfig 1.*

  host:
    - arrow-cpp
    - spdlog
    - yaml-cpp
    - gmock
    - gtest
    - libtins
    - fmt

  run:
    - {{ pin_compatible('arrow-cpp', max_pin='x') }}
    - {{ pin_compatible('spdlog', max_pin='x') }}
    - {{ pin_compatible('yaml-cpp', max_pin='x') }}
    - {{ pin_compatible('gmock', max_pin='x') }}
    - {{ pin_compatible('gtest', max_pin='x') }}
    - {{ pin_compatible('libtins', max_pin='x') }}
    - {{ pin_compatible('fmt', max_pin='x') }}

test:
  commands:
    - tests
    - tip_parse -h
    - parquet_video_extractor -h
    - tip_translate_1553 -h
    - tip_translate_arinc429 -h
    - pqcompare -h
    - bincompare -h
    - validate_yaml -h

about:
  home: https://github.com/309thEDDGE/tip.git
  summary: 'Fast IRIG 106 Chapter 10 CLI parser/translator'
  description: |
    Parse IRIG 106 Chapter 10 and export to Parquet files as intermediate data stores. 
    In a second (translation) stage, convert data in an intermediate data store to Engineering Units 
    (EU, ft, m/s, etc.) given an input file which conveys Interface Control Document 
    (ICD) data.  
  license: GPL-3.0-only AND BSD-4-Clause-UC
  license_file: licenses/
  dev_url: https://github.com/309thEDDGE/tip.git

extra:
  recipe-maintainers:
    - IM-USAF
    - RR-USAF
    - JR-USAF
