{% set name = "tip" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/309thEDDGE/tip/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ca6c7f4737b93b4a639a94506e3922e33c179933c26dc0d5a7029d96ff919911

build:
  skip: true  # [win and vc<14 or osx]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - ninja 1.*
    - cmake 3.*
    - pkgconfig 1.*

  host:
    - arrow-cpp
    - spdlog
    - yaml-cpp
    - gmock
    - gtest
    - libtins
    - fmt

  run:
    # Do not include spdlog, yaml-cpp, arrow-cpp, libtins, fmt
    # because those packages use run_exports to automatically
    # include runtime requirements.
    - {{ pin_compatible('gmock', max_pin='x.x.x') }}
    - {{ pin_compatible('gtest', max_pin='x.x.x') }}

test:
  commands:
    - tests
    - tip_parse -h
    - parquet_video_extractor -h
    - tip_translate_1553 -h
    - tip_translate_arinc429 -h
    - pqcompare -h
    - bincompare -h
    - validate_yaml -h

about:
  home: https://github.com/309thEDDGE/tip.git
  summary: Fast IRIG 106 Chapter 10 CLI parser/translator
  description: |
    Parse IRIG 106 Chapter 10 and export parsed, raw data to Parquet.
    In a second (translation) stage, convert raw data to Engineering Units 
    (EU, ft, m/s, etc.) given an input file which conveys Interface Control Document 
    (ICD) data.  
  license: GPL-3.0-only AND BSD-4-Clause-UC
  license_file: licenses/
  dev_url: https://github.com/309thEDDGE/tip.git

extra:
  recipe-maintainers:
    - IM-USAF
    - RR-USAF
    - JR-USAF
