{% set name = "tip" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/309thEDDGE/tip/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2aedafd3246013c98ba3d018c122ab926f0a6281dea5c4543e3c38c1ba0f1336

build:
  skip: true  # [win and vc<14 or osx]
  number: 2

requirements:
  build:
    - {{ compiler('cxx') }}
    - ninja 1.*
    - cmake 3.*
    - pkgconfig 1.*

  host:
    - arrow-cpp
    - spdlog
    - yaml-cpp
    - gmock
    - gtest
    - libtins
    - fmt

  run:
    - gmock
    - gtest

test:
  commands:
    - tests
    - tip_parse -h
    - parquet_video_extractor -h
    - tip_translate_1553 -h
    - tip_translate_arinc429 -h
    - pqcompare -h
    - bincompare -h
    - validate_yaml -h

about:
  home: https://github.com/309thEDDGE/tip.git
  summary: 'Fast IRIG 106 Chapter 10 CLI parser/translator'
  description: |
    Parse IRIG 106 Chapter 10 and export parsed, raw data to Parquet.
    In a second (translation) stage, convert raw data to Engineering Units 
    (EU, ft, m/s, etc.) given an input file which conveys Interface Control Document 
    (ICD) data.  
  license: GPL-3.0-only AND BSD-4-Clause-UC
  license_file: licenses/
  dev_url: https://github.com/309thEDDGE/tip.git

extra:
  recipe-maintainers:
    - IM-USAF
    - RR-USAF
    - JR-USAF
