{% set name = "tip" %}
{% set version = "3.0.4" %}

# appease linter
{% if libarrow is undefined %}
{% set libarrow = "14" %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/309thEDDGE/tip/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c32294cc80446a56857942e5a74861de18e5b8854b4c52ea3360ac8c6377e8fa
 
build:
  skip: true  # [win and vc<14 or osx]
  number: 8

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - ninja 1.*
    - cmake 3.*
    - pkgconfig 1.*

  host:
    - libarrow
    # arrow got split into more fine-grained packages as of v14
    {% if libarrow.split(".")[0] | int >= 14 %}
    - libparquet
    {% endif %}
    - spdlog
    - yaml-cpp
    - gmock
    - gtest
    - libtins
    - fmt

  run:
    - gmock
    - gtest

test:
  commands:
    - tests
    - tip parse -h
    - tip translate 1553 -h
    - tip translate arinc429 -h
    - tip util vidextract -h
    - tip util pqcomp -h
    - tip util bincomp -h
    - tip util validyaml -h

about:
  home: https://github.com/309thEDDGE/tip.git
  summary: 'Fast IRIG 106 Chapter 10 CLI parser/translator'
  description: |
    Parse IRIG 106 Chapter 10 and export parsed, raw data to Parquet.
    In a second (translation) stage, convert raw data to Engineering Units 
    (EU, ft, m/s, etc.) given an input file which conveys Interface Control Document 
    (ICD) data.  
  license: GPL-3.0-only AND BSD-4-Clause-UC
  license_file: licenses/
  dev_url: https://github.com/309thEDDGE/tip.git

extra:
  recipe-maintainers:
    - IM-USAF
    - RR-USAF
    - JR-USAF
